[package]
name = "rokr-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rokr-core = { path = "../rokr-core" }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
rand = "0.8"
keyring = "4.1.5"
open = "5.4.0"
sha2 = "0.11.0"

[dev-dependencies]
wiremock = { workspace = true }
tracing-subscriber = { workspace = true }
tempfile = { workspace = true }
